//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/Input/GameInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputAction"",
    ""maps"": [
        {
            ""name"": ""LobbyPlayerInputMap"",
            ""id"": ""22914133-17c8-4188-800c-69b6d054db52"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""61aac4d0-b23a-4b33-bbf4-cb7a74689e67"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraLook"",
                    ""type"": ""Value"",
                    ""id"": ""a21dd139-f6db-4a62-a242-c6d1b8b2cd27"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""26785724-cb7e-44b6-933a-a5b3a966d027"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LAttack"",
                    ""type"": ""Button"",
                    ""id"": ""176b72c7-256f-4420-9bcf-fdbbb42033af"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RAttack"",
                    ""type"": ""Button"",
                    ""id"": ""562d68e3-dc7c-445f-b4c7-2e6545caf068"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CallMouse"",
                    ""type"": ""Button"",
                    ""id"": ""d939609a-a27e-4d35-b0c4-3f86f8263bcb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""304e85fa-1003-4945-ba9f-0d7e29547ff5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5235e816-95c4-4ca6-910c-9d380c6ca72e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7d333b0a-7b39-42e7-91cb-376d1f3dafc6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9dde3af8-38e9-443e-bbcd-195241c26ed9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e6401f0d-8785-4ed5-b8fc-8abdd08703f1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e5c4695b-d070-4ec6-b861-bc286078529c"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bfbb63a-3a44-4d90-be58-77dea3911ec9"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.15,y=0.15)"",
                    ""groups"": """",
                    ""action"": ""CameraLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5021e1d5-a378-4e3f-932c-1a58763d78c4"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.75,y=0.75)"",
                    ""groups"": """",
                    ""action"": ""CameraLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a1d7f84-3bb9-4410-8c17-796de8a87c43"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0f8e20c-9435-4fb0-bdf8-4784500b11b2"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b7fd35e-4349-4c10-b2f2-9b509c9fa70c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c75d58d5-4bd8-498b-b856-32fbd020d544"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1571d8b1-5263-45d8-910f-dbd98ea21dc4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27cc361c-5873-4a4f-8e7b-a38d629d7896"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5404735e-98cc-4848-9d5c-18474c0a6ddf"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CallMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""BattlePlayerInputMap"",
            ""id"": ""b8d8650e-64e1-4a20-ac8d-107588117899"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""ec33d96b-249b-4462-bb49-9e7649dd19ac"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraLook"",
                    ""type"": ""Value"",
                    ""id"": ""9f61f13e-424e-431c-b6c6-2cf7a99f874e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LAttack"",
                    ""type"": ""Button"",
                    ""id"": ""e9b26942-80dd-434f-a5d2-6086e6739895"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialSkill1"",
                    ""type"": ""Button"",
                    ""id"": ""309f0dda-16ec-4a07-8d2b-4192c33e5ef4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f19c0d20-1e74-4e4f-9741-afe32efdfea6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""729fa7dc-d64a-4e10-b7fd-2141b1ee7c62"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4fe2e9bb-8537-421e-8062-71e76e0cd888"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""62f81fee-a632-411f-a52e-c8c7a12e8303"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1d1137d0-0fc6-49b6-bfe7-288bcf4c6492"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d6eec5a2-0c32-419e-b643-1c661c8f1b5c"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7f3d62c-6bd7-4145-875f-3d558cf8a3cd"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.15,y=0.15)"",
                    ""groups"": """",
                    ""action"": ""CameraLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73378c5b-cff9-4821-a400-9cb4803463b4"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.75,y=0.75)"",
                    ""groups"": """",
                    ""action"": ""CameraLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a661879-74a9-4e94-a33d-628050541688"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bef9a38-410e-42dc-b1de-ed049e6091ae"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fe88d5a-d354-4104-b0d5-9bbac4f11c7c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialSkill1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // LobbyPlayerInputMap
        m_LobbyPlayerInputMap = asset.FindActionMap("LobbyPlayerInputMap", throwIfNotFound: true);
        m_LobbyPlayerInputMap_Movement = m_LobbyPlayerInputMap.FindAction("Movement", throwIfNotFound: true);
        m_LobbyPlayerInputMap_CameraLook = m_LobbyPlayerInputMap.FindAction("CameraLook", throwIfNotFound: true);
        m_LobbyPlayerInputMap_Run = m_LobbyPlayerInputMap.FindAction("Run", throwIfNotFound: true);
        m_LobbyPlayerInputMap_LAttack = m_LobbyPlayerInputMap.FindAction("LAttack", throwIfNotFound: true);
        m_LobbyPlayerInputMap_RAttack = m_LobbyPlayerInputMap.FindAction("RAttack", throwIfNotFound: true);
        m_LobbyPlayerInputMap_CallMouse = m_LobbyPlayerInputMap.FindAction("CallMouse", throwIfNotFound: true);
        // BattlePlayerInputMap
        m_BattlePlayerInputMap = asset.FindActionMap("BattlePlayerInputMap", throwIfNotFound: true);
        m_BattlePlayerInputMap_Movement = m_BattlePlayerInputMap.FindAction("Movement", throwIfNotFound: true);
        m_BattlePlayerInputMap_CameraLook = m_BattlePlayerInputMap.FindAction("CameraLook", throwIfNotFound: true);
        m_BattlePlayerInputMap_LAttack = m_BattlePlayerInputMap.FindAction("LAttack", throwIfNotFound: true);
        m_BattlePlayerInputMap_SpecialSkill1 = m_BattlePlayerInputMap.FindAction("SpecialSkill1", throwIfNotFound: true);
    }

    ~@GameInputAction()
    {
        UnityEngine.Debug.Assert(!m_LobbyPlayerInputMap.enabled, "This will cause a leak and performance issues, GameInputAction.LobbyPlayerInputMap.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_BattlePlayerInputMap.enabled, "This will cause a leak and performance issues, GameInputAction.BattlePlayerInputMap.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // LobbyPlayerInputMap
    private readonly InputActionMap m_LobbyPlayerInputMap;
    private List<ILobbyPlayerInputMapActions> m_LobbyPlayerInputMapActionsCallbackInterfaces = new List<ILobbyPlayerInputMapActions>();
    private readonly InputAction m_LobbyPlayerInputMap_Movement;
    private readonly InputAction m_LobbyPlayerInputMap_CameraLook;
    private readonly InputAction m_LobbyPlayerInputMap_Run;
    private readonly InputAction m_LobbyPlayerInputMap_LAttack;
    private readonly InputAction m_LobbyPlayerInputMap_RAttack;
    private readonly InputAction m_LobbyPlayerInputMap_CallMouse;
    public struct LobbyPlayerInputMapActions
    {
        private @GameInputAction m_Wrapper;
        public LobbyPlayerInputMapActions(@GameInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_LobbyPlayerInputMap_Movement;
        public InputAction @CameraLook => m_Wrapper.m_LobbyPlayerInputMap_CameraLook;
        public InputAction @Run => m_Wrapper.m_LobbyPlayerInputMap_Run;
        public InputAction @LAttack => m_Wrapper.m_LobbyPlayerInputMap_LAttack;
        public InputAction @RAttack => m_Wrapper.m_LobbyPlayerInputMap_RAttack;
        public InputAction @CallMouse => m_Wrapper.m_LobbyPlayerInputMap_CallMouse;
        public InputActionMap Get() { return m_Wrapper.m_LobbyPlayerInputMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LobbyPlayerInputMapActions set) { return set.Get(); }
        public void AddCallbacks(ILobbyPlayerInputMapActions instance)
        {
            if (instance == null || m_Wrapper.m_LobbyPlayerInputMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LobbyPlayerInputMapActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @CameraLook.started += instance.OnCameraLook;
            @CameraLook.performed += instance.OnCameraLook;
            @CameraLook.canceled += instance.OnCameraLook;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @LAttack.started += instance.OnLAttack;
            @LAttack.performed += instance.OnLAttack;
            @LAttack.canceled += instance.OnLAttack;
            @RAttack.started += instance.OnRAttack;
            @RAttack.performed += instance.OnRAttack;
            @RAttack.canceled += instance.OnRAttack;
            @CallMouse.started += instance.OnCallMouse;
            @CallMouse.performed += instance.OnCallMouse;
            @CallMouse.canceled += instance.OnCallMouse;
        }

        private void UnregisterCallbacks(ILobbyPlayerInputMapActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @CameraLook.started -= instance.OnCameraLook;
            @CameraLook.performed -= instance.OnCameraLook;
            @CameraLook.canceled -= instance.OnCameraLook;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @LAttack.started -= instance.OnLAttack;
            @LAttack.performed -= instance.OnLAttack;
            @LAttack.canceled -= instance.OnLAttack;
            @RAttack.started -= instance.OnRAttack;
            @RAttack.performed -= instance.OnRAttack;
            @RAttack.canceled -= instance.OnRAttack;
            @CallMouse.started -= instance.OnCallMouse;
            @CallMouse.performed -= instance.OnCallMouse;
            @CallMouse.canceled -= instance.OnCallMouse;
        }

        public void RemoveCallbacks(ILobbyPlayerInputMapActions instance)
        {
            if (m_Wrapper.m_LobbyPlayerInputMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILobbyPlayerInputMapActions instance)
        {
            foreach (var item in m_Wrapper.m_LobbyPlayerInputMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LobbyPlayerInputMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LobbyPlayerInputMapActions @LobbyPlayerInputMap => new LobbyPlayerInputMapActions(this);

    // BattlePlayerInputMap
    private readonly InputActionMap m_BattlePlayerInputMap;
    private List<IBattlePlayerInputMapActions> m_BattlePlayerInputMapActionsCallbackInterfaces = new List<IBattlePlayerInputMapActions>();
    private readonly InputAction m_BattlePlayerInputMap_Movement;
    private readonly InputAction m_BattlePlayerInputMap_CameraLook;
    private readonly InputAction m_BattlePlayerInputMap_LAttack;
    private readonly InputAction m_BattlePlayerInputMap_SpecialSkill1;
    public struct BattlePlayerInputMapActions
    {
        private @GameInputAction m_Wrapper;
        public BattlePlayerInputMapActions(@GameInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_BattlePlayerInputMap_Movement;
        public InputAction @CameraLook => m_Wrapper.m_BattlePlayerInputMap_CameraLook;
        public InputAction @LAttack => m_Wrapper.m_BattlePlayerInputMap_LAttack;
        public InputAction @SpecialSkill1 => m_Wrapper.m_BattlePlayerInputMap_SpecialSkill1;
        public InputActionMap Get() { return m_Wrapper.m_BattlePlayerInputMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BattlePlayerInputMapActions set) { return set.Get(); }
        public void AddCallbacks(IBattlePlayerInputMapActions instance)
        {
            if (instance == null || m_Wrapper.m_BattlePlayerInputMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BattlePlayerInputMapActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @CameraLook.started += instance.OnCameraLook;
            @CameraLook.performed += instance.OnCameraLook;
            @CameraLook.canceled += instance.OnCameraLook;
            @LAttack.started += instance.OnLAttack;
            @LAttack.performed += instance.OnLAttack;
            @LAttack.canceled += instance.OnLAttack;
            @SpecialSkill1.started += instance.OnSpecialSkill1;
            @SpecialSkill1.performed += instance.OnSpecialSkill1;
            @SpecialSkill1.canceled += instance.OnSpecialSkill1;
        }

        private void UnregisterCallbacks(IBattlePlayerInputMapActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @CameraLook.started -= instance.OnCameraLook;
            @CameraLook.performed -= instance.OnCameraLook;
            @CameraLook.canceled -= instance.OnCameraLook;
            @LAttack.started -= instance.OnLAttack;
            @LAttack.performed -= instance.OnLAttack;
            @LAttack.canceled -= instance.OnLAttack;
            @SpecialSkill1.started -= instance.OnSpecialSkill1;
            @SpecialSkill1.performed -= instance.OnSpecialSkill1;
            @SpecialSkill1.canceled -= instance.OnSpecialSkill1;
        }

        public void RemoveCallbacks(IBattlePlayerInputMapActions instance)
        {
            if (m_Wrapper.m_BattlePlayerInputMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBattlePlayerInputMapActions instance)
        {
            foreach (var item in m_Wrapper.m_BattlePlayerInputMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BattlePlayerInputMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BattlePlayerInputMapActions @BattlePlayerInputMap => new BattlePlayerInputMapActions(this);
    public interface ILobbyPlayerInputMapActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCameraLook(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnLAttack(InputAction.CallbackContext context);
        void OnRAttack(InputAction.CallbackContext context);
        void OnCallMouse(InputAction.CallbackContext context);
    }
    public interface IBattlePlayerInputMapActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCameraLook(InputAction.CallbackContext context);
        void OnLAttack(InputAction.CallbackContext context);
        void OnSpecialSkill1(InputAction.CallbackContext context);
    }
}
